version: '2'
services:
  wekan:
    image: mquandalle/wekan
    links: 
      - wekandb
    environment:
      - MONGO_URL=mongodb://wekandb/wekan
      - ROOT_URL=http://wekan.hos777.org:8989
    ports:
      - 8989:8080

    restart: always 


  wekandb:
    image: mongo:4.1.5
    volumes:
      - test_db:/data/db
    restart: always

volumes:
  test_db:
